login.scenario1.username=
login.scenario1.password=secret_sauce
login.scenario1.error=Epic sadface: Username is required

login.scenario2.username=standard_user
login.scenario2.password=
login.scenario2.error=Epic sadface: Password is required

login.scenario3.username=standard_user
login.scenario3.password=wrong_pass
login.scenario3.error=Epic sadface: Username and password do not match any user in this service

login.scenario4.username=locked_out_user
login.scenario4.password=secret_sauce
login.scenario4.error=Epic sadface: Sorry, this user has been locked out.